'use client';
import { useState } from 'react';
import { KeyRound, LockKeyhole, LogOut, Save } from 'lucide-react';

type ProductRow={id:string;titulo:string;preco:number;preco_de:number|null;ativo:boolean;estoque:number|null};
type BannerRow={id:string;titulo:string;subtitulo:string|null;imagem_url:string|null;link:string|null;ordem:number;ativo:boolean};
type QuestionRow={id:string;texto:string;ordem:number};
type AdminData={products:ProductRow[];orders:Record<string,unknown>[];leads:Record<string,unknown>[];banners:BannerRow[];questions:QuestionRow[]};
export default function AdminPage(){const[logged,setLogged]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[data,setData]=useState<AdminData|null>(null);
 async function load(){setMsg('');try{const r=await fetch('/api/admin',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.message||'Acesso administrativo não configurado.');setData(d as AdminData);setLogged(true)}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível carregar o painel.')}}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'login',email:f.get('email'),password:f.get('password')})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível entrar.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Falha de acesso.')}finally{setBusy(false)}}
 async function save(action:string,id:string,patch:Record<string,unknown>){setMsg('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,id,patch})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível salvar.');setMsg('Alteração salva.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Falha ao salvar.')}}
 async function logout(){await fetch('/api/admin',{method:'DELETE'});setLogged(false);setData(null);setMsg('Sessão encerrada.');}
 return <main className="section"><div className="wrap admin-shell"><span className="eyebrow">Área protegida</span><h1 className="page-title">Administração Bom Lar</h1><p className="muted">Acesso seguro ao catálogo, campanhas, quiz, pedidos e leads.</p>{!logged?<form onSubmit={login} className="panel" style={{maxWidth:430,marginTop:25}}><h2><KeyRound size={18} style={{display:'inline',verticalAlign:'middle',marginRight:7}}/>Entrar com Supabase Auth</h2><div className="field"><label>E-mail</label><input name="email" type="email" required autoComplete="username"/></div><div className="field" style={{marginTop:12}}><label>Senha</label><input name="password" type="password" required autoComplete="current-password"/></div>{msg&&<p className="notice error-notice">{msg}</p>}<button className="btn-primary" style={{marginTop:16}} disabled={busy}><LockKeyhole size={15}/>{busy?'Verificando…':'Acessar painel'}</button><p className="muted" style={{fontSize:10}}>O usuário precisa da função administrativa `app_metadata.role = admin`; sem isso, o acesso é negado.</p></form>:<><div className="admin-head"><p className="muted">Sessão autenticada</p><button className="option" onClick={logout}><LogOut size={14}/> Sair</button></div>{msg&&<p className="notice" role="status">{msg}</p>}{data&&<>
    <div className="admin-grid"><div className="admin-stat"><span>Produtos</span><b>{data.products.length}</b></div><div className="admin-stat"><span>Pedidos recentes</span><b>{data.orders.length}</b></div><div className="admin-stat"><span>Leads recentes</span><b>{data.leads.length}</b></div></div>
    <section className="panel admin-section"><h2>Produtos e preços</h2><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Produto</th><th>Preço (R$)</th><th>Ativo</th><th></th></tr></thead><tbody>{data.products.map(p=><tr key={p.id}><td>{p.titulo}</td><td><input className="admin-input" type="number" min="0" step="0.01" defaultValue={p.preco} id={`price-${p.id}`}/></td><td><input type="checkbox" defaultChecked={p.ativo} id={`active-${p.id}`}/></td><td><button className="icon-button" aria-label={`Salvar ${p.titulo}`} onClick={()=>save('update_product',p.id,{preco:Number((document.getElementById(`price-${p.id}`) as HTMLInputElement).value),ativo:(document.getElementById(`active-${p.id}`) as HTMLInputElement).checked})}><Save size={14}/></button></td></tr>)}</tbody></table></div></section>
    <section className="panel admin-section"><h2>Banners</h2><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Título</th><th>Subtítulo</th><th>Imagem URL</th><th>Link</th><th>Ativo</th><th></th></tr></thead><tbody>{data.banners.map(b=><tr key={b.id}><td><input className="admin-input" defaultValue={b.titulo} id={`bt-${b.id}`}/></td><td><input className="admin-input" defaultValue={b.subtitulo??''} id={`bs-${b.id}`}/></td><td><input className="admin-input" defaultValue={b.imagem_url??''} id={`bi-${b.id}`}/></td><td><input className="admin-input" defaultValue={b.link??''} id={`bl-${b.id}`}/></td><td><input type="checkbox" defaultChecked={b.ativo} id={`ba-${b.id}`}/></td><td><button className="icon-button" aria-label={`Salvar banner ${b.titulo}`} onClick={()=>save('update_banner',b.id,{titulo:(document.getElementById(`bt-${b.id}`) as HTMLInputElement).value,subtitulo:(document.getElementById(`bs-${b.id}`) as HTMLInputElement).value||null,imagem_url:(document.getElementById(`bi-${b.id}`) as HTMLInputElement).value||null,link:(document.getElementById(`bl-${b.id}`) as HTMLInputElement).value||null,ativo:(document.getElementById(`ba-${b.id}`) as HTMLInputElement).checked})}><Save size={14}/></button></td></tr>)}</tbody></table></div></section>
    <section className="panel admin-section"><h2>Perguntas do quiz</h2><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Ordem</th><th>Texto</th><th></th></tr></thead><tbody>{data.questions.map(q=><tr key={q.id}><td>{q.ordem}</td><td><input className="admin-input" defaultValue={q.texto} id={`qt-${q.id}`}/></td><td><button className="icon-button" aria-label={`Salvar pergunta ${q.ordem}`} onClick={()=>save('update_question',q.id,{texto:(document.getElementById(`qt-${q.id}`) as HTMLInputElement).value})}><Save size={14}/></button></td></tr>)}</tbody></table></div></section>
    <section className="panel admin-section"><h2>Pedidos recentes</h2><pre className="admin-json">{JSON.stringify(data.orders,null,2)}</pre></section>
    <section className="panel admin-section"><h2>Leads recentes</h2><pre className="admin-json">{JSON.stringify(data.leads,null,2)}</pre></section>
  </>}</>}</div></main>;
}
