'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, LockKeyhole, MapPin, ShieldCheck } from 'lucide-react';
import type { Product } from '@/lib/types';
import { formatBRL } from '@/lib/format';
import { useCart } from '@/components/cart';
import { trackMeta } from '@/components/meta-pixel';

const addonUnitPrice=(product:Product)=>product.price+(product.variants.find(v=>v.available!==false)?.priceExtra??0);

export function CheckoutForm({addons,checkoutEnabled=false}:{addons:Product[];checkoutEnabled?:boolean}){
 const{lines,total,clear}=useCart();const[added,setAdded]=useState<string[]>([]);const[payment,setPayment]=useState('pix');const[loading,setLoading]=useState(false);const[message,setMessage]=useState('');const[messageType,setMessageType]=useState<'error'|'success'>('error');const[cep,setCep]=useState('');const[address,setAddress]=useState({street:'',neighborhood:'',city:'',state:''});const[exitOpen,setExitOpen]=useState(false);const[exitChecked,setExitChecked]=useState(false);const[exitAccepted,setExitAccepted]=useState(false);
 const addonTotal=useMemo(()=>addons.filter(a=>added.includes(a.slug)).reduce((s,a)=>s+addonUnitPrice(a)*(exitAccepted&&a.slug===addons[0]?.slug?0.9:1),0),[addons,added,exitAccepted]);const fullTotal=total+addonTotal;const offer=addons[0];
 useEffect(()=>{if(!checkoutEnabled)return;const onExit=(e:MouseEvent)=>{if(e.clientY<=0&&lines.length&&!sessionStorage.getItem('bomlar-exit-seen')){sessionStorage.setItem('bomlar-exit-seen','1');setExitOpen(true)}};const onPop=()=>{if(!sessionStorage.getItem('bomlar-back-seen')&&lines.length){sessionStorage.setItem('bomlar-back-seen','1');setExitOpen(true);history.pushState({checkout:true},'','#checkout')}};history.pushState({checkout:true},'','#checkout');const timer=window.setTimeout(()=>window.addEventListener('mouseout',onExit),500);window.addEventListener('popstate',onPop);return()=>{clearTimeout(timer);window.removeEventListener('mouseout',onExit);window.removeEventListener('popstate',onPop)}},[lines.length,checkoutEnabled]);
 const lookupCep=async()=>{const clean=cep.replace(/\D/g,'');if(clean.length!==8)return;try{const r=await fetch(`https://viacep.com.br/ws/${clean}/json/`);const d=await r.json();if(d.erro){setMessage('CEP não encontrado. Confira os números.');setMessageType('error');return}setAddress({street:d.logradouro??'',neighborhood:d.bairro??'',city:d.localidade??'',state:d.uf??''});setMessage('Endereço preenchido pelo CEP.');setMessageType('success')}catch{setMessage('Não foi possível consultar o CEP agora. Preencha o endereço manualmente.');setMessageType('error')}};
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!lines.length){setMessage('Sua sacola está vazia. Escolha um produto antes de finalizar.');return}trackMeta('InitiateCheckout',{value:fullTotal,currency:'BRL',num_items:lines.reduce((n,l)=>n+l.quantity,0)});setLoading(true);setMessage('');const form=new FormData(e.currentTarget);const items=lines.map(l=>({slug:l.product.slug,quantity:l.quantity,variant:l.variant})).concat(addons.filter(a=>added.includes(a.slug)).map(a=>({slug:a.slug,quantity:1,variant:a.variants.find(v=>v.available!==false)?.value,downsell:exitAccepted&&a.slug===offer?.slug})));const payload={cliente_nome:String(form.get('name')||''),telefone:String(form.get('phone')||''),email:String(form.get('email')||''),endereco:{cep,logradouro:address.street,bairro:address.neighborhood,cidade:address.city,uf:address.state,numero:String(form.get('number')||''),complemento:String(form.get('complement')||'')},payment,items,downsellAccepted:exitAccepted};try{const r=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.saved){setMessage(d.message||'A conexão de pedidos ainda não está pronta; nenhum pedido foi registrado.');setMessageType('error')}else{setMessage(`Pedido ${d.orderId} registrado por ${formatBRL(d.total)}. O pagamento aguarda a integração do gateway.`);setMessageType('success');clear()}}catch{setMessage('Não foi possível confirmar o pedido agora. Nenhuma cobrança foi realizada.');setMessageType('error')}finally{setLoading(false)}}
 if(!lines.length&&messageType!=='success')return <div className="panel"><p className="muted">Sua sacola está vazia. Escolha um achadinho para continuar.</p><Link className="btn-primary" href="/#produtos">Voltar à loja</Link></div>;
 if(!checkoutEnabled)return <div className="panel"><span className="eyebrow">Nenhum pedido será enviado</span><h2 className="page-title" style={{fontSize:24}}>Estamos conectando o sistema de pedidos.</h2><p className="muted">O checkout ainda não está ativo. Seu carrinho permanece salvo neste navegador; seus dados pessoais não serão solicitados e nenhuma cobrança será feita.</p><div style={{margin:'20px 0'}}>{lines.map(line=><div className="checkout-summary-line" key={`${line.product.id}:${line.variant??''}`}><span>{line.quantity} × {line.product.title}{line.variant?` · ${line.variant}`:''}</span><b>{formatBRL((line.product.price+(line.product.variants.find(v=>v.value===line.variant)?.priceExtra??0))*line.quantity)}</b></div>)}<div className="checkout-summary-line" style={{fontWeight:700}}><span>Total parcial</span><b>{formatBRL(total)}</b></div></div><Link className="btn-primary" href="/#produtos">Continuar na loja</Link></div>;
 return <div className="checkout-layout"><form className="panel" onSubmit={submit}><h2>Seus dados</h2><div className="form-grid"><Field label="Nome completo"><input name="name" required autoComplete="name" placeholder="Como podemos chamar você?"/></Field><Field label="WhatsApp"><input name="phone" required autoComplete="tel" inputMode="tel" placeholder="(11) 99999-9999"/></Field><Field label="E-mail"><input name="email" required type="email" autoComplete="email" placeholder="voce@email.com"/></Field><Field label="CEP"><div style={{display:'flex',gap:8}}><input value={cep} onChange={e=>setCep(e.target.value)} onBlur={lookupCep} inputMode="numeric" autoComplete="postal-code" placeholder="00000-000" required pattern="[0-9]{5}-?[0-9]{3}"/><button type="button" className="icon-button" onClick={lookupCep} aria-label="Buscar CEP"><MapPin size={16}/></button></div></Field><Field label="Endereço" full><input value={address.street} onChange={e=>setAddress({...address,street:e.target.value})} autoComplete="street-address" required placeholder="Rua ou avenida"/></Field><Field label="Bairro"><input value={address.neighborhood} onChange={e=>setAddress({...address,neighborhood:e.target.value})} required placeholder="Bairro"/></Field><Field label="Número"><input name="number" required placeholder="Nº"/></Field><Field label="Cidade"><input value={address.city} onChange={e=>setAddress({...address,city:e.target.value})} required placeholder="Cidade"/></Field><Field label="UF"><input value={address.state} onChange={e=>setAddress({...address,state:e.target.value})} required maxLength={2} minLength={2} placeholder="SP"/></Field><Field label="Complemento (opcional)" full><input name="complement" placeholder="Apto, bloco, referência"/></Field></div>
 <h2 style={{marginTop:27}}>Forma de pagamento</h2><div className="payment-choice"><label><input type="radio" name="payment" checked={payment==='pix'} onChange={()=>setPayment('pix')}/> Pix</label><label><input type="radio" name="payment" checked={payment==='card'} onChange={()=>setPayment('card')}/> Cartão</label></div><p className="muted" style={{fontSize:10}}>Pagamento preparado para integração. Nenhuma cobrança é processada nesta prévia.</p>
 {message&&<p className={`notice ${messageType==='success'?'success-notice':'error-notice'}`} role="status">{message}</p>}<button className="btn-primary checkout-submit" type="submit" disabled={loading}>{loading?'Verificando…':<> <LockKeyhole size={15}/> Finalizar compra · {formatBRL(fullTotal)}</>}</button>
 <div className="panel" style={{marginTop:13,padding:16,background:'#101010'}}><h2 style={{fontSize:14,marginBottom:10}}>Complete sua compra</h2><p className="muted" style={{fontSize:10,marginTop:0}}>Pequenos complementos para deixar tudo no lugar.</p>{addons.length?addons.map(a=><label className="addon-row" key={a.id}><img src={a.images[0]} alt={a.title}/><span><strong>{a.title}</strong><span>{formatBRL(addonUnitPrice(a))}</span></span><input type="checkbox" checked={added.includes(a.slug)} onChange={e=>{setAdded(e.target.checked?[...new Set([...added,a.slug])]:added.filter(s=>s!==a.slug));if(a.slug===offer?.slug&&!e.target.checked){setExitAccepted(false);setExitChecked(false)}}} aria-label={`Adicionar ${a.title}`}/></label>):<p className="muted" style={{fontSize:11}}>Os complementos entre R$ 9 e R$ 29 aparecerão aqui quando o catálogo completo estiver conectado.</p>}{addons.length===1&&<p className="muted" style={{fontSize:9}}>Esta amostra contém um complemento real; novas opções dependem da sincronização do catálogo completo.</p>}</div>
 <p style={{fontSize:9,color:'#8b8d93',textAlign:'center'}}><ShieldCheck size={13} style={{display:'inline',verticalAlign:'middle',marginRight:4}}/> Seus dados são enviados de forma protegida.</p></form>
 <aside><div className="panel"><h2>Resumo do pedido</h2>{lines.map(l=><div className="checkout-summary-line" key={l.product.id}><span>{l.quantity} × {l.product.title}</span><b>{formatBRL((l.product.price+(l.product.variants.find(v=>v.value===l.variant)?.priceExtra??0))*l.quantity)}</b></div>)}{addons.filter(a=>added.includes(a.slug)).map(a=><div className="checkout-summary-line" key={a.id}><span>1 × {a.title}{exitAccepted&&a.slug===offer?.slug?' · 10% off':''}</span><b>{formatBRL(addonUnitPrice(a)*(exitAccepted&&a.slug===offer?.slug?0.9:1))}</b></div>)}<div className="checkout-summary-line"><span>Frete</span><b>{fullTotal>=99?'Grátis':'Calculado pelo CEP'}</b></div><div className="checkout-summary-line" style={{fontWeight:700}}><span>Total</span><b>{formatBRL(fullTotal)}</b></div><p className="muted" style={{fontSize:10}}>Frete grátis em compras a partir de R$ 99.</p></div></aside>
 {exitOpen&&<div className="downsell-modal" role="dialog" aria-modal="true" aria-labelledby="downsell-title"><div className="downsell-card"><span className="eyebrow">Uma última condição</span><h2 id="downsell-title">Leve um complemento com 10% de desconto.</h2><p className="muted" style={{fontSize:12}}>A oferta aparece uma vez nesta sessão e só será adicionada se você marcar a opção.</p>{offer?<label className="addon-row"><img src={offer.images[0]} alt={offer.title}/><span><strong>{offer.title}</strong><span><del>{formatBRL(addonUnitPrice(offer))}</del> <b>{formatBRL(addonUnitPrice(offer)*0.9)}</b></span></span><input type="checkbox" checked={exitChecked} onChange={e=>setExitChecked(e.target.checked)} aria-label={`Aceitar complemento com 10% de desconto`}/></label>:<p className="muted">Nenhum complemento elegível está disponível.</p>}<div className="downsell-actions"><button className="btn-primary" onClick={()=>{if(exitChecked&&offer){setAdded([...new Set([...added,offer.slug])]);setExitAccepted(true)}setExitOpen(false)}}>{exitChecked?'Adicionar com 10% off':'Continuar sem extra'}</button><button className="option" onClick={()=>setExitOpen(false)}>Agora não</button></div></div></div>}
 </div>;
}
function Field({label,children,full}:{label:string,children:React.ReactNode,full?:boolean}){return <div className={`field ${full?'full':''}`}><label>{label}</label>{children}</div>}
