import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';
import he from 'he';
import { createHash } from 'node:crypto';

const BASE=(process.env.CATALOG_SOURCE_URL||'https://lojamaxlarapp.com').replace(/\/$/,'');
const SUPABASE_URL=process.env.SUPABASE_URL;
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const BUCKET='produtos';
if(!SUPABASE_URL||!SERVICE_KEY){console.error('Importação interrompida: SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY são necessários no ambiente do servidor.');process.exit(1);}
const supabase=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});

type ShopifyImage={src?:string;alt?:string};
type ShopifyVariant={id:number|string;title?:string;price:string;compare_at_price?:string|null;inventory_quantity?:number;available?:boolean;option1?:string|null;option2?:string|null;option3?:string|null};
type ShopifyProduct={id:number|string;handle?:string;title:string;body_html?:string;product_type?:string;tags?:string[]|string;images?:ShopifyImage[];variants?:ShopifyVariant[];options?:{name:string}[]};
type ShopifyCollection={id:number|string;title:string;handle:string;sort_order?:string};
type ReviewData={rating:number|null;count:number;reviews:{author:string;body:string;rating:number;date:string|null}[]};
function safeText(value:string){let text=value;for(const tag of ['script','style']){let lower=text.toLowerCase();let start=lower.indexOf(`<${tag}`);while(start>=0){const end=lower.indexOf(`</${tag}>`,start);if(end<0){text=text.slice(0,start);break;}text=text.slice(0,start)+' '+text.slice(end+tag.length+3);lower=text.toLowerCase();start=lower.indexOf(`<${tag}`);}}return he.decode(text.replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim().replace(/max\s*lar/ig,'Bom Lar');}
const slugify=(value:string)=>safeText(value).normalize('NFKD').replace(new RegExp('['+String.fromCharCode(0x300)+'-'+String.fromCharCode(0x36f)+']','g'),'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function fetchJson<T>(url:string):Promise<T>{let last:unknown;for(let attempt=0;attempt<3;attempt++){try{const response=await fetch(url,{headers:{'User-Agent':'BomLarCatalogImporter/1.0','Accept':'application/json'},signal:AbortSignal.timeout(45000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json() as T;}catch(error){last=error;await delay(400*(attempt+1));}}throw last instanceof Error?last:new Error('Falha de consulta externa');}
async function fetchList<T>(path:string,key:string):Promise<T[]>{const out:T[]=[];for(let page=1;page<=50;page++){const url=`${BASE}${path}${path.includes('?')?'&':'?'}limit=250&page=${page}`;const data=await fetchJson<Record<string,T[]>>(url);const rows=data[key]??[];out.push(...rows);if(rows.length<250)break;}return out;}
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T,index:number)=>Promise<R>):Promise<R[]>{const result=new Array<R>(items.length);let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const i=cursor++;if(i>=items.length)return;result[i]=await fn(items[i],i);}}));return result;}
function imageSource(value:string){try{const url=new URL(value);return url.protocol==='https:'&&(['cdn.shopify.com','images.shopifycdn.net'].includes(url.hostname)||url.hostname.endsWith('.shopifycdn.com'))?url:null;}catch{return null;}}
async function ensureBucket(){const endpoint=`${SUPABASE_URL}/storage/v1/bucket`;const headers={apikey:SERVICE_KEY!,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json'};const body=JSON.stringify({id:BUCKET,name:BUCKET,public:true,file_size_limit:12582912,allowed_mime_types:['image/webp']});const response=await fetch(endpoint,{method:'POST',headers,body});if(response.ok)return;if(response.status===409||response.status===400){const update=await fetch(`${endpoint}/${BUCKET}`,{method:'PUT',headers,body});if(update.ok)return;}throw new Error('Não foi possível preparar o bucket público produtos.');}
async function downloadAsWebp(src:string){const url=imageSource(src);if(!url)throw new Error('Host de imagem fora da lista autorizada');const r=await fetch(url,{signal:AbortSignal.timeout(45000),headers:{'User-Agent':'BomLarCatalogImporter/1.0'}});if(!r.ok)throw new Error(`Imagem HTTP ${r.status}`);const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length>60*1024*1024)throw new Error('Imagem excede 60 MiB');return sharp(bytes).rotate().resize({width:1800,height:1800,fit:'inside',withoutEnlargement:true}).webp({quality:84,effort:4}).toBuffer();}
async function uploadImage(path:string,bytes:Buffer){const encoded=path.split('/').map(encodeURIComponent).join('/');const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${encoded}`,{method:'PUT',headers:{apikey:SERVICE_KEY!,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'image/webp','x-upsert':'true'},body:new Uint8Array(bytes)});if(!r.ok)throw new Error(`Storage HTTP ${r.status}`);return `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${encoded}`;}
function emptyReview():ReviewData{return{rating:null,count:0,reviews:[]};}
function findReviewNode(node:unknown,out:ReviewData){if(Array.isArray(node)){for(const x of node)findReviewNode(x,out);return;}if(!node||typeof node!=='object')return;const o=node as Record<string,unknown>;if(o['@graph'])findReviewNode(o['@graph'],out);if(o.aggregateRating&&typeof o.aggregateRating==='object'){const a=o.aggregateRating as Record<string,unknown>;const rating=Number(a.ratingValue);const count=Number(a.reviewCount??a.ratingCount);if(Number.isFinite(rating)&&rating>=0&&rating<=5)out.rating=rating;if(Number.isFinite(count)&&count>=0)out.count=Math.round(count);}const reviews=o.review;if(Array.isArray(reviews)){for(const review of reviews){if(!review||typeof review!=='object')continue;const r=review as Record<string,unknown>;const ar=r.reviewRating as Record<string,unknown>|undefined;const rating=Number(ar?.ratingValue);const author=typeof r.author==='string'?r.author:typeof r.author==='object'&&r.author?String((r.author as Record<string,unknown>).name??''):'';const body=typeof r.reviewBody==='string'?safeText(r.reviewBody):'';if(body&&Number.isFinite(rating)&&rating>=0&&rating<=5&&out.reviews.length<20)out.reviews.push({author:safeText(author).slice(0,100),body:body.slice(0,700),rating,date:typeof r.datePublished==='string'?r.datePublished:null});}}}
async function readReviews(handle:string):Promise<ReviewData>{try{const r=await fetch(`${BASE}/products/${encodeURIComponent(handle)}`,{headers:{'User-Agent':'BomLarCatalogImporter/1.0'},signal:AbortSignal.timeout(20000)});if(!r.ok)return emptyReview();const html=await r.text();const result=emptyReview();for(const match of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{findReviewNode(JSON.parse(match[1]),result);}catch{}}return result;}catch{return emptyReview();}}
function inferredCategory(product:ShopifyProduct,collectionName?:string){const raw=safeText(collectionName||product.product_type||'Organização');return raw||'Organização';}

async function main(){
 console.log('Carregando todas as coleções e produtos públicos…');
 const [collections,products]=await Promise.all([fetchList<ShopifyCollection>('/collections.json','collections'),fetchList<ShopifyProduct>('/collections/all/products.json','products')]);
 const bestSellerCollection=collections.find(c=>c.handle==='mais-vendidos');
 const bestSellerProducts=bestSellerCollection?await fetchList<{id:number|string}>(`/collections/${encodeURIComponent(bestSellerCollection.handle)}/products.json`,'products').catch(()=>[]):[];
 const bestSellerIds=new Set(bestSellerProducts.map(p=>String(p.id)));
 const productCollection=new Map<string,string>();
 const categoryCollections=collections.filter(collection=>!['frontpage','mais-vendidos','all'].includes(collection.handle));
 await mapLimit(categoryCollections,4,async collection=>{const rows=await fetchList<{id:number|string}>(`/collections/${encodeURIComponent(collection.handle)}/products.json`,'products').catch(()=>[]);for(const p of rows)if(!productCollection.has(String(p.id)))productCollection.set(String(p.id),safeText(collection.title));return true;});
 const normalized=new Map<string,ShopifyProduct>();let duplicateCount=0;for(const p of products){const id=String(p.id);if(!id||normalized.has(id)){duplicateCount++;continue;}normalized.set(id,p);}
 const all=[...normalized.values()];const usedSlugs=new Set<string>();const slugById=new Map<string,string>();for(const p of all){const id=String(p.id);const base=slugify(p.title)||`produto-${slugify(id)}`;let slug=base;if(usedSlugs.has(slug))slug=`${base.slice(0,78)}-${slugify(id).slice(0,10)}`;if(usedSlugs.has(slug))slug=`produto-${slugify(id)}`;usedSlugs.add(slug);slugById.set(id,slug);}const categoryNames=[...new Set(all.map(p=>inferredCategory(p,productCollection.get(String(p.id)))))];
 const categoryRows=categoryNames.map((nome,ordem)=>({nome,slug:slugify(nome),ordem}));
 const{data:categoryData,error:categoryError}=await supabase.from('categorias').upsert(categoryRows,{onConflict:'slug'}).select('id,nome,slug');if(categoryError||!categoryData)throw new Error('Falha ao gravar categorias; confira a migration e permissões.');
 const categoryId=new Map(categoryData.map(c=>[c.nome,c.id]));
 await ensureBucket();
 let imported=0,imageCount=0,reviewCount=0,failed=0,skippedImages=0;let processed=0;
 await mapLimit(all,3,async source=>{try{
  const slug=slugById.get(String(source.id));if(!slug)throw new Error('Slug indisponível');const title=safeText(source.title);const description=safeText(source.body_html??'');const category=inferredCategory(source,productCollection.get(String(source.id)));const variants=source.variants??[];const variantPrices=variants.map(v=>Number(v.price)).filter(n=>Number.isFinite(n)&&n>=0);if(!variantPrices.length)throw new Error('Preço inválido');const basePrice=Math.min(...variantPrices);
  const review=await readReviews(source.handle??slug);const compare=variants.map(v=>Number(v.compare_at_price)).filter(n=>Number.isFinite(n)&&n>0);const maxCompare=compare.length?Math.max(...compare):null;const comparePrice=maxCompare!==null&&maxCompare>basePrice?maxCompare:null;
  const tags=typeof source.tags==='string'?source.tags.split(',').map(s=>safeText(s)).filter(Boolean):Array.isArray(source.tags)?source.tags.map(s=>safeText(s)).filter(Boolean):[];if(bestSellerIds.has(String(source.id))&&!tags.some(tag=>tag.toLowerCase()==='mais-vendido'))tags.push('mais-vendido');
  const variantsToStore=variants.map(v=>({nome:(source.options??[]).map(o=>safeText(o.name)).filter(Boolean).join(' / ')||'Opção',valor:safeText(v.title||'Padrão'),preco_extra:Math.max(0,Number(v.price||basePrice)-basePrice),disponivel:typeof v.available==='boolean'?v.available:null}));
  const sourceImages=(source.images??[]).map(i=>i.src).filter((s):s is string=>Boolean(s));if(!sourceImages.length)throw new Error('Produto sem fotos acessíveis');const uploaded:string[]=[];let productImageFailures=0;
  for(let i=0;i<sourceImages.length;i++){try{const bytes=await downloadAsWebp(sourceImages[i]);const hash=createHash('sha1').update(sourceImages[i]).digest('hex').slice(0,8);uploaded.push(await uploadImage(`${slug}/${String(i+1).padStart(3,'0')}-${hash}.webp`,bytes));}catch{skippedImages++;productImageFailures++;}}
  if(productImageFailures>0||uploaded.length!==sourceImages.length)throw new Error('Galeria incompleta; produto não foi marcado como importado');
  const exactStocks=variants.map(v=>v.inventory_quantity).filter((n):n is number=>typeof n==='number'&&Number.isInteger(n)&&n>=0);const available=variants.some(v=>v.available===true);const stockSum=exactStocks.reduce((a,b)=>a+b,0);const exactStock=exactStocks.length?(stockSum>0?stockSum:available?null:0):null;
  const{data:product,error}=await supabase.from('produtos').upsert({origem_id:String(source.id),titulo:title,slug,descricao:description,preco:Math.min(...variantPrices),preco_de:comparePrice,categoria_id:categoryId.get(category)??null,tags,ativo:true,estoque:exactStock,disponivel:available,avaliacao_media:review.rating,total_avaliacoes:review.count,avaliacoes:review.reviews},{onConflict:'origem_id'}).select('id').single();if(error||!product)throw new Error('Falha ao gravar produto');
  await supabase.from('produto_imagens').delete().eq('produto_id',product.id);if(uploaded.length){const imageRows=uploaded.map((url,ordem)=>({produto_id:product.id,url,ordem}));const{error:e}=await supabase.from('produto_imagens').insert(imageRows);if(e)throw new Error('Falha ao vincular imagens');}
  await supabase.from('produto_variacoes').delete().eq('produto_id',product.id);if(variantsToStore.length){const{error:e}=await supabase.from('produto_variacoes').insert(variantsToStore.map(v=>({...v,produto_id:product.id})));if(e)throw new Error('Falha ao gravar variações');}
  imported++;imageCount+=uploaded.length;if(review.rating!==null)reviewCount++;
 }catch{failed++;}finally{processed++;if(processed%10===0||processed===all.length)console.log(`Produtos processados: ${processed}/${all.length}; importados: ${imported}; falhas: ${failed}; fotos: ${imageCount}`);}});
 console.log(JSON.stringify({sourceProducts:products.length,categories:categoryData.length,productsImported:imported,productImagesStored:imageCount,productsWithRatings:reviewCount,duplicatesSkipped:duplicateCount,imagesSkipped:skippedImages,productsFailed:failed,bucket:BUCKET,report:'Importação concluída; valores de marca de origem foram substituídos, banners/logos externos foram excluídos.'},null,2));
 if(failed>0)process.exitCode=2;
}
main().catch(()=>{console.error('Importação interrompida antes do relatório completo. Verifique migration, chave protegida e disponibilidade da origem; nenhum segredo foi registrado.');process.exit(1);});
