import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';

const sessionCookie='bomlar_admin_session';
const env=()=>({url:process.env.SUPABASE_URL,key:process.env.SUPABASE_ANON_KEY,service:process.env.SUPABASE_SERVICE_ROLE_KEY});
function response(message:string,status=400){return NextResponse.json({message},{status});}
async function adminClient(){const c=await cookies();const token=c.get(sessionCookie)?.value;const{url,key,service}=env();if(!url||!key||!token)return null;const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await auth.auth.getUser(token);if(error||!data.user||data.user.app_metadata?.role!=='admin'||!service)return null;return createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function POST(req:Request){const input=await req.json().catch(()=>null);if(!input||typeof input!=='object')return response('Dados inválidos.',400);const record=input as Record<string,unknown>;const action=record.action;
 if(action==='login'){const parsed=z.object({email:z.string().email(),password:z.string().min(8).max(200)}).safeParse(record);if(!parsed.success)return response('Confira e-mail e senha.',400);const{url,key}=env();if(!url||!key)return response('As variáveis Supabase ainda não foram aplicadas ao ambiente.',503);const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await auth.auth.signInWithPassword(parsed.data);if(error||!data.session||data.user.app_metadata?.role!=='admin')return response('Acesso não autorizado. Verifique as credenciais e a função administrativa.',401);const c=await cookies();c.set(sessionCookie,data.session.access_token,{httpOnly:true,secure:true,sameSite:'none',path:'/',maxAge:Math.min(data.session.expires_in??3600,3600)});return NextResponse.json({ok:true});}
 const db=await adminClient();if(!db)return response('Sessão administrativa inválida ou chave de servidor ainda não configurada.',403);const id=z.string().uuid().safeParse(record.id);if(!id.success)return response('Identificador inválido.',400);
 if(action==='update_product'){const patch=z.object({titulo:z.string().min(1).max(200).optional(),preco:z.number().nonnegative().optional(),preco_de:z.number().nonnegative().nullable().optional(),descricao:z.string().max(10000).optional(),ativo:z.boolean().optional(),estoque:z.number().int().nonnegative().nullable().optional()}).safeParse(record.patch);if(!patch.success)return response('Alteração de produto inválida.',400);const{error}=await db.from('produtos').update(patch.data).eq('id',id.data);if(error)return response('Não foi possível atualizar o produto.',503);return NextResponse.json({ok:true});}
 if(action==='update_banner'){const patch=z.object({titulo:z.string().min(1).max(200).optional(),subtitulo:z.string().max(500).nullable().optional(),imagem_url:z.string().url().nullable().optional(),link:z.string().max(500).nullable().optional(),ordem:z.number().int().optional(),ativo:z.boolean().optional()}).safeParse(record.patch);if(!patch.success)return response('Alteração de banner inválida.',400);const{error}=await db.from('banners').update(patch.data).eq('id',id.data);if(error)return response('Não foi possível atualizar o banner.',503);return NextResponse.json({ok:true});}
 if(action==='update_question'){const patch=z.object({texto:z.string().min(1).max(300).optional(),ordem:z.number().int().optional()}).safeParse(record.patch);if(!patch.success)return response('Alteração de pergunta inválida.',400);const{error}=await db.from('quiz_perguntas').update(patch.data).eq('id',id.data);if(error)return response('Não foi possível atualizar a pergunta.',503);return NextResponse.json({ok:true});}
 return response('Ação não reconhecida.',400);
}
export async function GET(){const db=await adminClient();if(!db)return response('Painel aguardando sessão administrativa e segredo de servidor.',503);const[products,orders,leads,banners,questions]=await Promise.all([db.from('produtos').select('id,titulo,slug,preco,preco_de,ativo,estoque').order('titulo'),db.from('pedidos').select('id,cliente_nome,email,telefone,itens,total,status,downsell_aceito,criado_em').order('criado_em',{ascending:false}).limit(100),db.from('leads').select('id,nome,whatsapp,origem,criado_em').order('criado_em',{ascending:false}).limit(100),db.from('banners').select('*').order('ordem'),db.from('quiz_perguntas').select('*').order('ordem')]);if([products,orders,leads,banners,questions].some(r=>r.error))return response('Não foi possível consultar os dados administrativos.',503);return NextResponse.json({products:products.data,orders:orders.data,leads:leads.data,banners:banners.data,questions:questions.data});}
export async function DELETE(){const c=await cookies();c.delete(sessionCookie);return NextResponse.json({ok:true});}
